### PR TITLE
Move ConnPlotter code from NEST to a separate repository

### LINKED ISSUE #1971: Move ConnPlotter from NEST code base to separate package
The ConnPlotter packages included in the NEST code base is not an integral part of NEST, just an additional tool. I suggest to remove it from the NEST code base and turn it into an independent Python package hosted under github.com/nest.

@jougs @terhorstd Any comments?

### PR DESCRIPTION
**Pull request by pnbabu**
Fixes [#1971](https://github.com/nest/nest-simulator/issues/1971)

This PR moves all the files related to `ConnPlotter` from `nest-simulator` repo.

### CODE REVIEW

**Review by jougs — COMMENTED** [review]
Looks mostly good. I'm wondering a bit if the toplevel Python files (other than `setup.py`, that is) should go into their own `src` or `nest-connplotter` directory instead of being toplevel.

I'd also like to hear @heplesser's feedback as original author before merging

**Comment by jougs** [comment]
And I think that `examples/__init__.py` can go. It does not have anything useful.

**Review by heplesser — COMMENTED** [review]
This move is fine with me. "examples" is currently set up as a package, thus `examples/__init__.py`.  But having it as a package does not really make sense, so the `__init__.py` should be removed. This has consequences:

- `connplotter_tutorial.py` relies on examples being a package, but that should be easily fixed. 
- Also `setup.py` treats examples as a package and needs to be adjusted to ensure that the examples will be installed.

Finally, the tutorial is in a very outdated literal programming format, it would be great to convert it to a notebook or our standard style for examples.

**Comment by pnbabu** [comment]
Removed `examples/__init__.py` and updated the tutorial and `setup.py` accordingly.

I am trying to run the tutorial locally on my machine and it is taking a long time to run. I will investigate what is taking time. @heplesser  When you say `standard style`, are you referring to `pynest/examples` in the NEST repo?

**Comment by Helveg** [comment]
Oh I think I did some duplicate things in #2. Some things that should be taken from there:

* `import matplotlib.font_manager`, not all version of matplotlib import this when mpl is imported and an `AttributeError` can occur (happened to me on v3.4.3)
* In `setup.py`:
  * Replace `from distutils.core` with `from setuptools`; distutils is problematic and deprecated (will be removed in Python 3.12). `distutils` packages cannot be uninstalled by `pip` for example.
  * Remove the `package_dir` argument and place source code files into a `ConnPlotter` or `nest_connplotter` directory, then just give `packages=["nest_connplotter"]` for simplified and conventional packaging.
* Add a `.gitignore`

**Comment by jougs** [comment]
Work and discussion continues in #2.

**Pull request closed without merging**
